### ISSUE TITLE
Error while installing with pip

### ISSUE THREAD

**Issue by ricardobarroslourenco** [mikekeith52/scalecast#29]
I have got this error while running `pip install --upgrade scalecast`  in a fresh new environment created with mambaconda (with only jupyterlab coming preinstalled):

```
(scalecast) ricardo@ricardo-XPS-8940:~$ pip install --upgrade scalecast
Collecting scalecast
  Using cached SCALECAST-0.15.12.tar.gz (680 kB)
  Preparing metadata (setup.py) ... done
Collecting scikit-learn
  Using cached scikit_learn-1.2.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.5 MB)
Collecting scalecast
  Using cached SCALECAST-0.15.11.tar.gz (680 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.15.10.tar.gz (680 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.15.9.tar.gz (679 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.15.8.tar.gz (679 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.15.7.tar.gz (677 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.15.6.tar.gz (411 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.15.5.tar.gz (410 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.15.4.tar.gz (408 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.15.3.tar.gz (408 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.15.2.tar.gz (408 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.15.1.tar.gz (403 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.15.0.tar.gz (400 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.14.8.tar.gz (382 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.14.7.tar.gz (368 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.14.6.tar.gz (368 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.14.5.tar.gz (368 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.14.4.tar.gz (368 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.14.3.tar.gz (367 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.14.1.tar.gz (346 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.14.0.tar.gz (268 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.13.11.tar.gz (257 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.13.10.tar.gz (256 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.13.9.tar.gz (256 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.13.8.tar.gz (256 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.13.6.tar.gz (245 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.13.5.tar.gz (245 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.13.4.tar.gz (244 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.13.3.tar.gz (242 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.13.2.tar.gz (242 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.13.1.tar.gz (242 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.13.0.tar.gz (232 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.12.9.tar.gz (230 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.12.8.tar.gz (229 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.12.7.tar.gz (228 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.12.6.tar.gz (226 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.12.5.tar.gz (132 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.12.4.tar.gz (131 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.12.3.tar.gz (130 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.11.2.tar.gz (1.1 MB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.11.1.tar.gz (2.5 MB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.11.0.tar.gz (1.0 MB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.10.5.tar.gz (1.0 MB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.10.4.tar.gz (1.0 MB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.10.3.tar.gz (1.0 MB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.10.2.tar.gz (1.1 MB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.10.1.tar.gz (1.0 MB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.10.0.tar.gz (1.1 MB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.9.9.tar.gz (1.0 MB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.9.8.tar.gz (397 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.9.7.tar.gz (397 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.9.6.tar.gz (397 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.9.4.tar.gz (396 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.9.2.tar.gz (791 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.9.1.tar.gz (395 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.9.0.tar.gz (785 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.8.4.tar.gz (389 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.8.3.tar.gz (389 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.8.2.tar.gz (389 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.8.1.tar.gz (389 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.8.0.tar.gz (389 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.7.6.tar.gz (388 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.7.5.tar.gz (388 kB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.7.4.tar.gz (3.6 MB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.7.3.tar.gz (3.6 MB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.7.2.tar.gz (22.1 MB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.7.1.tar.gz (54.0 MB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.7.0.tar.gz (27.0 MB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.6.9.tar.gz (27.0 MB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.6.8.tar.gz (29.3 MB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.6.7.tar.gz (59.1 MB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.6.6.tar.gz (54.4 MB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.6.4.tar.gz (45.2 MB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.6.2.tar.gz (45.2 MB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.6.1.tar.gz (45.1 MB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.6.0.tar.gz (44.2 MB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.5.9.tar.gz (44.4 MB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.5.8.tar.gz (43.9 MB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.5.7.tar.gz (43.9 MB)
  Preparing metadata (setup.py) ... done
  Using cached SCALECAST-0.5.6.tar.gz (24.8 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-db64hpf6/scalecast_da5dfa67998b4328acbac9c7a883f4c5/setup.py", line 6, in <module>
          shutil.copy('./examples/eCommerce.ipynb','./docs/source/Forecaster/examples/eCommerce.ipynb')
        File "/home/ricardo/mambaforge/envs/scalecast/lib/python3.11/shutil.py", line 419, in copy
          copyfile(src, dst, follow_symlinks=follow_symlinks)
        File "/home/ricardo/mambaforge/envs/scalecast/lib/python3.11/shutil.py", line 258, in copyfile
          with open(dst, 'wb') as fdst:
               ^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: './docs/source/Forecaster/examples/eCommerce.ipynb'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```
It seems that a missing jupyter notebook is causing the issue. Can you check it?

**Comment by mikekeith52** [comment]
It is iterating through all scalecast versions to find one that works. See https://github.com/pypa/pip/issues/9284. Can you try `pip install scalecast==0.15.11`?

**Comment by ricardobarroslourenco** [comment]
It seems that it doesn't resolve the TensorFlow dependency (it can be the usage of mambaforge). Which version of TensorFlow scalecast depends on?

```
(scalecast) ricardo@ricardo-XPS-8940:~$ pip install scalecast==0.15.11
Collecting scalecast==0.15.11
  Using cached SCALECAST-0.15.11.tar.gz (680 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: scikit-learn in ./mambaforge/envs/scalecast/lib/python3.11/site-packages (from scalecast==0.15.11) (1.2.0)
ERROR: Could not find a version that satisfies the requirement tensorflow (from scalecast) (from versions: none)
ERROR: No matching distribution found for tensorflow
```

**Comment by ricardobarroslourenco** [comment]
After installing TensorFlow manually with pip it solved in a second run. It is weird to understand why pip is not resolving that dependency though.

**Comment by mikekeith52** [comment]
Yes I need to look into it more. Thank you for bringing it to my attention! Closing this issue for now.
